import {RouteGroupInfo, RouteInfo} from './sidebar.metadata';


export const ROUTE_GROUPS: RouteGroupInfo[] = [
    {
        title: 'Operations',
        path: '',
        langKey: 'operations',
        routeKey: 'operations',
        icon: 'ft-briefcase',
        class: '',
        badge: '',
        isExternalLink: false,
    },
    {
        title: 'Master',
        path: '',
        langKey: 'master',
        routeKey: 'master',
        icon: 'ft-lock',
        class: '',
        badge: '',
        isExternalLink: false,
    },
];


export const ROUTES: RouteInfo[] = [ // admin
    {
        path: '/home',
        title: 'Dashboard',
        titleKey: 'dashboard', // !!NEW this is the language key.
        icon: 'ft-layout',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        userGroup: '100',
        routeGroupKey: 'operations',
    },
    {
        path: '/users',
        title: 'Users',
        titleKey: 'users',
        icon: 'ft-users',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        userGroup: '100',
        routeGroupKey: 'master',
    },
    {
        path: '',
        title: 'Menu Levels',
        icon: 'ft-align-left',
        class: 'has-sub',
        badge: '1',
        badgeClass: 'badge badge-pill badge-danger float-right mr-1 mt-1',
        isExternalLink: false,
        userGroup: '100',
        routeGroupKey: 'master',
        submenu: [
            {
                path: 'javascript:;',
                title: 'Second Level',
                icon: '',
                class: '',
                badge: '',
                badgeClass: '',
                isExternalLink: true,
                submenu: [],
                userGroup: '100',
                routeGroupKey: 'master',
            },
            {
                path: '',
                title: 'Second Level Child',
                icon: '',
                class: 'has-sub',
                badge: '',
                badgeClass: '',
                isExternalLink: false,
                userGroup: '100',
                routeGroupKey: 'master',
                submenu: [
                    {
                        path: 'javascript:;',
                        title: 'Third Level 1.1',
                        icon: '',
                        class: '',
                        badge: '',
                        badgeClass: '',
                        isExternalLink: true,
                        submenu: [],
                        userGroup: '100',
                        routeGroupKey: 'master',
                    },
                    {
                        path: 'javascript:;',
                        title: 'Third Level 1.2',
                        icon: '',
                        class: '',
                        badge: '',
                        badgeClass: '',
                        isExternalLink: true,
                        submenu: [],
                        userGroup: '100',
                        routeGroupKey: 'master',
                    },
                ]
            },
        ]
    },
    {
        path: '/languages',
        title: 'Languages',
        icon: 'ft-layout',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        userGroup: '100',
        routeGroupKey: 'master',
        // routeGroupKey: 'operations',
    },
];
